id: IF4727D54
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T14:54:51+00:00'
last_modified: '2022-06-16T05:43:36.249911+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7854
  title: སྔགས་རིམ་ཆེན་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E4BE:
      image_group_id: I1KG9240
      title: Volume 1 of sngags rim chen mo/
      total_pages: 734
      order: 1
      base_file: E4BE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
